NUMPY


In [4]:
import  numpy   as  np

creating a numpy array

In [5]:
# using  python list form  to numpy array using  np.array method  
arr = np.array([1,2,3,4,5,6,7]) 
print(arr)
type(arr)

# Using arrange  method  this function was like python  range function but returns numpy array 
arr = np.arange(0,12,2,float)
print(arr)

#using zeroes() and ones()  by using this we will crete  array  with zeroes and ones 
zero_array = np.zeros((3,3))
print(zero_array)

ones_array = np.ones((2,4))
print(ones_array)

#using linespace Generate  evenly spaced  array with a specified  intervels 
line_space_array = np.linspace(0,20,5,0,0,int)
print(line_space_array)



[1 2 3 4 5 6 7]
[ 0.  2.  4.  6.  8. 10.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  4  8 12 16]


Array Opearations 


In [6]:
# Element wise opearations its  support operations like add , sub, mult, div 
arr1= np.array([1,2,3,4,5,6])
arr2 = np.array([8,9,10,11,12,13])

sub_of_arr =arr1 + arr2 
print(sub_of_arr)

mult_of_arr=arr1 * arr2
print(mult_of_arr)

div_of_array = arr1/arr2
print(div_of_array)


[ 9 11 13 15 17 19]
[ 8 18 30 44 60 78]
[0.125      0.22222222 0.3        0.36363636 0.41666667 0.46153846]


Universal functions 

In [7]:
arr= np.array([1,2,3,4])

#square root of an array 
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

#Exponentions 
exp_arr= np.exp(arr)
print(exp_arr)

# Broadcasting for example you can add scalar to an array 
arr2= arr+ 5
print(arr2)


[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[6 7 8 9]


Array Reshaping 

In [14]:
# You can reshape array to fit diffrent dimentions 
print(arr)
reshaped_arr = arr.reshape(2,2)
print(reshaped_arr)

#Flatening an array convert an multidimentional array in to 1d array 
flattened_arr =  reshaped_arr.flatten()
print(flattened_arr)


[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


Indexing and  slicing 


In [ ]:
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr[2])

3


In [ ]:
#slicing 
print(arr[1:4]) # last index was exclusive 

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1:-1])

[2 3 4]
[[4 5 6]]


In [ ]:
#Statistical  operations 
arr =np.array([1,2,3,4,5,6,7,8,9])

#mean of the array 
mean= np.mean(arr)
print(f"Mean of arr {mean}")

max = np.max(arr)
print (max)

#standered  deviations 
std_dev = np.std(arr)
print(std_dev)


Mean of arr 5.0
9
2.581988897471611


In [24]:
#Random Numbers with python  
random_arr = np.random.random((2,20))
print(random_arr)

#Random Integer
randome_int_arr = np.random.randint(1,10,(2,10))
print(randome_int_arr)

[[0.97545646 0.16157958 0.87088307 0.06042369 0.10118972 0.44399699
  0.34590218 0.21194887 0.14866119 0.56250548 0.29570893 0.15515252
  0.45714637 0.00216673 0.53022932 0.0132174  0.7919988  0.81661159
  0.86799279 0.73602219]
 [0.90559927 0.45277289 0.72968854 0.99201165 0.28752428 0.94627757
  0.3764268  0.71567375 0.32790566 0.21863679 0.65190385 0.92858919
  0.20456095 0.00522211 0.37207496 0.59444005 0.15974498 0.71666522
  0.87084298 0.10930105]]
[[5 8 8 1 7 8 4 2 3 5]
 [4 8 9 9 4 6 5 6 8 8]]
